### ISSUE TITLE
Wire Approve Tokens modal

### ISSUE THREAD

**Issue by flppv** [onomyprotocol/otrust#119]
<img width="493" alt="Approve okens" src="https://user-images.githubusercontent.com/6984143/123263347-89e37180-d501-11eb-9d37-9bf80ed18e9c.png">

New modal was added, with mocked data, we need to integrate it.

**Comment by bbshark99** [comment]
@flppv I assume this should be closed. 

PR: https://github.com/onomyprotocol/otrust/pull/141
