### ISSUE TITLE
Add Bridge Modal integration

### ISSUE THREAD

**Issue by cgdusek** [onomyprotocol/otrust#129]
This is the issue to track the bridge modal integration.

**Comment by dzmitryhil** [comment]
Updated readme with:

  - grpc samples (just some samples and proto files required for the new client) - **Tools/GRPC** samples in the [readme](https://github.com/dzmitryhil/gravity-bridge/tree/dzmitryhil/grpc-bridge-client-sample/deploy/single-node-runner-rinkeby) 
  
  - client description - **Client / Bridge** client description in [readme](https://github.com/dzmitryhil/gravity-bridge/tree/dzmitryhil/grpc-bridge-client-sample/deploy/single-node-runner-rinkeby) 

If you don't see the branch, check the main plz, the same location "deploy/single-node-runner-rinkeby" or ping me in Discord. 

The doc will help to implement integration with the bridge.
  
@AndriiBlagodyr  @flppv, guys, I know that you are not responsible for the BFF implementation, but could you propagate the links to the implementor, plz.

**Comment by flppv** [comment]
@Shing-Ho @james-lin71 @bbshark99
