### ISSUE TITLE
Add in The Graph api to expose historical Transaction events

### ISSUE THREAD

**Issue by cgdusek** [onomyprotocol/otrust#16]

**Comment by cgdusek** [comment]
This is where the data for the Bonding Curve originates: https://github.com/onomyprotocol/otrust/blob/master/src/components/Chart/D3Chart.js

**Comment by cgdusek** [comment]
We will want to make the data available through a context component.  Could possibly use the chain context: https://github.com/onomyprotocol/otrust/blob/master/src/context/chain/ChainContext.js

**Comment by tpikachu** [comment]
Let's use the apollo client to query the data from our subgraph endpint

**Comment by cgdusek** [comment]
Yes, plan to use Apollo. Created the OnomyProtocol/ograph-rinkeby and am now transferring over your code from the other repo

**Comment by cgdusek** [comment]
Data exposed here: 
https://github.com/onomyprotocol/otrust/blob/bb2afbcd7fe454fe8bfb8cf82873baf6ea478f9b/src/components/Chart/D3Chart.js#L73

Data structure can be viewed on browser by looking for this console.log:
https://github.com/onomyprotocol/otrust/blob/bb2afbcd7fe454fe8bfb8cf82873baf6ea478f9b/src/components/Chart/D3Chart.js#L98
