### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by cgdusek** [onomyprotocol/otrust#2]
Need to include instructions for development environment.

1) Install and run Ganache: npm install ganache
2) Install Metamask on browser and connect Ganache
3) Clone both the Solonomy and the Otrust to the same root folder
4) cd Solonomy and then npm install
5) npm install truffle
6) truffle deploy
7) cd .. cd Otrust
8) npm install
9) npm run

**Comment by tpikachu** [comment]
I think hardhat is more comfortable than truffle. What about migrating to hardhat?
