### ISSUE TITLE
update bridge description logic

### ISSUE THREAD

**Issue by laloknows** [onomyprotocol/otrust#260]
**1. If user has not approved any bNOM for bridging, then description must read:** 

"You must approve (amount) bNOM for bridging to the Onomy Network. Your bNOM will be burned and you will receive an equivalent number of NOM tokens in your Onomy Wallet. After approval, you may submit a bridge transaction!"

**2. If user has approved bNOM and enters an amount to bridge within the approved amount, proceed as normal (no changes here)**

**3. If a user has approved bNOM and enters an amount to bridge OVER the approved amount, then description must read:**

You have approved bridging of up to  (approved) bNOM. To bridge (amount entered) bNOM, you must approve at least an additional (amount - approved) bNOM.

**Comment by AlexOnomy** [comment]
Closed with https://github.com/onomyprotocol/otrust/pull/261
