### ISSUE TITLE
Text not re-rendering causing multiple ghost labels

### ISSUE THREAD

**Issue by cgdusek** [onomyprotocol/otrust#3]
https://github.com/onomyprotocol/otrust/blob/e47cecfed5151aa26f45bf7fe7520c1df19adbc1/src/components/Chart/D3LineChart.js#L119

**Comment by linghong** [comment]
Could you explain in a more detailed way what is wrong?  I don't know blockchain. 

I did see an error after initial load and errors  when I input amount and clicking the Execute button on console
![Screen Shot 2021-03-04 at 4 06 33 PM](https://user-images.githubusercontent.com/5419448/110030401-ab76de00-7d03-11eb-8244-67ba7b697cc4.png)

**Comment by cgdusek** [comment]
Are you able to see how the rerender of the x-axis label didn't wipe the previous render?

![image](https://user-images.githubusercontent.com/38732970/110031262-4b306e00-7cfc-11eb-9dad-79cce5d49298.png)

**Comment by linghong** [comment]
I think I have to add coins  onto the wallet, after that maybe I can see what you are seeing.
