### ISSUE TITLE
Clicking MAX does not make calculation

### ISSUE THREAD

**Issue by laloknows** [onomyprotocol/otrust#61]
![image](https://user-images.githubusercontent.com/76499838/117556219-89b41300-b034-11eb-909d-7a278ba3b37f.png)
![image](https://user-images.githubusercontent.com/76499838/117556271-0c3cd280-b035-11eb-9a1d-359b5d911418.png)

**Comment by Shing-Ho** [comment]
https://github.com/onomyprotocol/otrust/pull/66
