### ISSUE TITLE
Cannot sell NOM, UNPREDICTABLE_GAS_LIMIT

### ISSUE THREAD

**Issue by laloknows** [onomyprotocol/otrust#62]
happens when trying to sell NOM for ETH. does not matter if you place a slippage limit or not. 

Additional issue that may be related is that the Sell Approval modal is not appearing before confirming sell

![image](https://user-images.githubusercontent.com/76499838/117556292-3a221700-b035-11eb-8c40-1a29ec85520d.png)

**Comment by Shing-Ho** [comment]
Maybe, we will need to set the slippage as 1% as default

**Comment by Shing-Ho** [comment]
https://github.com/onomyprotocol/otrust/pull/65
