### ISSUE TITLE
Update links bottom of right panel

### ISSUE THREAD

**Issue by laloknows** [onomyprotocol/otrust#78]
About Onomy = https://onomy.io

Twitter Icon linking to https://twitter.com/onomyprotocol
Telegram Icon linking to https://t.me/onomyprotocol

**Comment by laloknows** [comment]
@flppv or @Shing-Ho could you make this quick update? thanks!

**Comment by flppv** [comment]
Will do, also will update icons

**Comment by Rostyslavmp** [comment]
Already updated but with About, Medium, and Twitter.
Telegram should be added.

**Comment by flppv** [comment]
Telegram is added now
