### ISSUE TITLE
selling amount = to approved amount still asks to approve

### ISSUE THREAD

**Issue by laloknows** [onomyprotocol/otrust#81]
![image](https://user-images.githubusercontent.com/76499838/119359189-5bab1180-bc77-11eb-8e91-4a909da6cc8f.png)

63570.10118845 is approved. Entered 63570.10118845 and still asks to approve.

**Comment by Shing-Ho** [comment]
I believe we discussed adding several options when users approve for select maximum and specific amount. Where we are currently? @laloknows @cgdusek @relictos

**Comment by laloknows** [comment]
@Shing-Ho Anton is pushing updated approval process screens shortly that should solve the issues once we integrate those. I'll close this!
