### ISSUE TITLE
Setting MAX gives decimal value error

### ISSUE THREAD

**Issue by laloknows** [onomyprotocol/otrust#82]
![image](https://user-images.githubusercontent.com/76499838/119367217-b8aac580-bc7f-11eb-94c3-9751e8419735.png)

![image](https://user-images.githubusercontent.com/76499838/119367071-9618ac80-bc7f-11eb-9108-34c01b774e52.png)

**Comment by Shing-Ho** [comment]
Is @cgdusek checking this issue?
