### ISSUE TITLE
Add USD conversion to tx confirmation screeen

### ISSUE THREAD

**Issue by laloknows** [onomyprotocol/otrust#84]
The confirmation screen shows the NOM/ETH rate, which will be a tiny and difficult fraction to remember. For enhanced UX, it would be best to add a USD conversion next to "Exchange Rate"

![image](https://user-images.githubusercontent.com/76499838/119376524-0c221100-bc8a-11eb-9998-7d5ee5d772ec.png)

![image](https://user-images.githubusercontent.com/76499838/119377015-9e2a1980-bc8a-11eb-89a4-f7e06fb65cf9.png)

**Comment by cgdusek** [comment]
Need Anton to implement design

**Comment by cgdusek** [comment]
Need to get Uniswap contract pulling USDC/ETH price point
https://github.com/onomyprotocol/otrust/blob/bd73d6bcd47b2f96ac28faaa06bc2f4579730d34/src/context/chain/ChainContext.js#L57
