### ISSUE TITLE
Change network confirmations to "1" on confirmation screen

### ISSUE THREAD

**Issue by laloknows** [onomyprotocol/otrust#85]
When the tx confirmation screen appears, this means at least one confirmation has appeared on the blockchain. 

Naturally, we should default the Tx Confirmation screen to say "1" rather than "0"

![image](https://user-images.githubusercontent.com/76499838/119377980-b77f9580-bc8b-11eb-84e2-0f83781f33fa.png)

**Comment by cgdusek** [comment]
https://github.com/onomyprotocol/otrust/commit/48e07de772f3ea56b201dc61a8b96bd3a97f202b
