### ISSUE TITLE
NO LIMIT slippage still fails

### ISSUE THREAD

**Issue by laloknows** [onomyprotocol/otrust#87]
selecting NO LIMIT on slippage still fails. Selecting 1, 2.5, or 5% all work

![image](https://user-images.githubusercontent.com/76499838/119378681-8489d180-bc8c-11eb-8595-b0edeecf6f26.png)

**Comment by laloknows** [comment]
@cgdusek this happens when user selects "max" because there's no more ETH to use as gas. This is at least one of the cases

**Comment by cgdusek** [comment]
https://github.com/onomyprotocol/otrust/commit/6777bc809ac351be17ba6b0adee1bf291c3b15a4
