### ISSUE TITLE
Setting MAX on sell = NOT ENOUGH NOM bug

### ISSUE THREAD

**Issue by laloknows** [onomyprotocol/otrust#88]
Setting MAX On sell side creates not enough nom bug even if previously approved.

This is likely because the MAX button truncates and rounds up at some point, so there's a very small amount that is not actually approved and prevents user from selling.

![image](https://user-images.githubusercontent.com/76499838/119379316-58bb1b80-bc8d-11eb-9d5f-b5f5b51af903.png)

As you can see, when the very last digit is changed from 7 to 6 now it allows selling:

![image](https://user-images.githubusercontent.com/76499838/119379485-8902ba00-bc8d-11eb-9490-a248b8819b24.png)

**Comment by Rostyslavmp** [comment]
can't reproduce, maybe we should down round the amount, not just round
