### ISSUE TITLE
Add Web3React connectors

### ISSUE THREAD

**Issue by cgdusek** [onomyprotocol/otrust#9]
https://github.com/NoahZinsmeister/web3-react/tree/v6/example

The example shows where they have integrated many of the connectors. We want to think how to add these options to the autologin page in a responsive, easy to use manner

**Comment by cgdusek** [comment]
https://github.com/onomyprotocol/otrust/blob/master/src/context/AutoLogin.js

Autologin source code

**Comment by cgdusek** [comment]
Autologin landing page

https://github.com/onomyprotocol/otrust/blob/master/src/pages/Landing.js

**Comment by Shing-Ho** [comment]
assign to me

**Comment by cgdusek** [comment]
Assigned

**Comment by Shing-Ho** [comment]
@cgdusek 
Should I show modal after the user click `connect to wallet` then do we need to show 5 options to letting users click it?
Currently, seems like it's auto-connecting the metamask now.

**Comment by cgdusek** [comment]
Please remove Web3Modal and use the example from Web3React: https://github.com/NoahZinsmeister/web3-react/tree/v6/example

**Comment by cgdusek** [comment]
![image](https://user-images.githubusercontent.com/38732970/111209491-15ac4000-859a-11eb-8a51-5557d5fe59ff.png)

**Comment by Shing-Ho** [comment]
https://github.com/onomyprotocol/otrust/pull/19

**Comment by cgdusek** [comment]
Dev branch has been patched to allow for functionality development with Metamask.  The code that was intended for this issue is not functioning correctly.
