### ISSUE TITLE
can't input decimal when buying/selling

### ISSUE THREAD

**Issue by laloknows** [onomyprotocol/otrust#95]
Test wallet had .5 ETH. Decimal points are being counted as disallowed characters. I could not purchase any wNOM because I couldn't type the decimal point

![image](https://user-images.githubusercontent.com/76499838/120428537-cfb57b80-c341-11eb-8774-6e0a2a3de4cd.png)

**Comment by laloknows** [comment]
also can't input "0" to type "0.5" for example.

**Comment by cgdusek** [comment]
https://github.com/onomyprotocol/otrust/commit/b3ef9d698a77c9f76445edf54b3d1cf2605dbbe2
