### ISSUE TITLE
Confirming without selecting slippage limit

### ISSUE THREAD

**Issue by laloknows** [onomyprotocol/otrust#96]
If user clicks "confirm" without selecting a slippage limit, then an error is triggered. 

To enhance UX, select one of two options:

1. Select No Limit by default
2. Force user to select slippage limit before proceeding. If they try to click "Confirm" without selecting slippage, highlight slippage limit in red and note "You must select slippage limit to confirm."

![image](https://user-images.githubusercontent.com/76499838/120429079-cbd62900-c342-11eb-83a2-4e7cbfcbfab1.png)

**Comment by Shing-Ho** [comment]
What about disable confirm button if user didn't select slippage?

**Comment by Shing-Ho** [comment]
@laloknows

**Comment by Shing-Ho** [comment]
@laloknows https://github.com/onomyprotocol/otrust/issues/96#issuecomment-853006859
Could you reply to here?

**Comment by Shing-Ho** [comment]
I think it's better to disable the confirm button.

**Comment by cgdusek** [comment]
Yes, disable the button unless the select slippage. On the button say “Select Slippage”

**Comment by Shing-Ho** [comment]
So on the button, it should show Select Slippage(34s)?

**Comment by Shing-Ho** [comment]
I think just disable the button will make sense to the user. They will find a way to enable the buttton.

**Comment by cgdusek** [comment]
I think Lalo would like a modal better. Notifying them to select a slippage if it hasn’t been selected. Use requestfailed modal

**Comment by laloknows** [comment]
Keep it as confirm on the button. Add in red text "*Required to Proceed

**Comment by Shing-Ho** [comment]
https://github.com/onomyprotocol/otrust/pull/97
